steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --target
      - deploy
      - --tag=gcr.io/$PROJECT_ID/batch:$BUILD_ID
      - --build-arg
      - _ENTRYPOINT=entrypoint/batch/main.go
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/batch:$BUILD_ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta
      - container
      - clusters
      - get-credentials
      - app-cluster
      - --zone=asia-northeast1-a
      - --project=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - cronjob/proceed-work-status-batch
      - proceed-work-status-container=gcr.io/$PROJECT_ID/batch:$BUILD_ID
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=app-cluster'