# https://kamihikouki.hatenablog.com/entry/2019/03/08/211622
# の問題があるため、Job系はProxyなしでSQLに繋ぐ
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: proceed-work-status-batch
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        metadata:
          name: proceed-work-status
        spec:
          restartPolicy: Never
          containers:
            - name: proceed-work-status-container
              image: ${BATCH_IMAGE}
              command: ["./main", "proceed-work-status"]
              env:
                - name: GO_ENV
                  value: /var/secrets/batch-env
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/gcp/credentials.json
                - name: FIREBASE_CREDENTIALS
                  value: /var/secrets/firebase/credentials.json
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /var/secrets/gcp
                  readOnly: true
                - name: firebase-credentials
                  mountPath: /var/secrets/firebase
                  readOnly: true
                - name: batch-env
                  mountPath: /var/secrets
                  readOnly: true
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials
            - name: firebase-credentials
              secret:
                secretName: firebase-credentials
            - name: batch-env
              secret:
                secretName: batch-env