# https://kamihikouki.hatenablog.com/entry/2019/03/08/211622
# の問題があるため、Job系はProxyなしでSQLに繋ぐ
---
apiVersion: batch/v1
kind: Job
metadata:
  name: reindex-search-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: reindex-search
    spec:
      restartPolicy: Never
      containers:
        - name: reindex-search-container
          image: ${IMAGE}
          command: ["./main", "reindex-search"]
          env:
            - name: GO_ENV
              value: /var/secrets/env
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp/credentials.json
            - name: FIREBASE_CREDENTIALS
              value: /var/secrets/firebase/credentials.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/gcp
              readOnly: true
            - name: firebase-credentials
              mountPath: /var/secrets/firebase
              readOnly: true
            - name: env
              mountPath: /var/secrets
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
        - name: env
          secret:
            secretName: env
